### ISSUE TITLE
cortex-m-rt v0.7.0? 

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32l0xx-hal#198] opened 2021-12-05 22:51 UTC
Any chance of updating to use `cortex-m-rt v0.7.0`? That may also need updating to `stm32l0 v0.14.0` and other changes.

If anyone can point me to a branch that has this update then I can reactivate testing my examples (https://github.com/pdgilbert/rust-integration-testing/actions) with `stm32l0xx-hal`. I have had to disable it because of the conflict with other crates now using the newer `cortex-m-rt`.

**Comment by jamwaffles** [comment] 2021-12-06 09:37
I did the upgrade in a fork of this repo a while back, but found a regression with the timers. I opened https://github.com/stm32-rs/stm32-rs/pull/659 to fix, but there's been no movement on that so far.

**Comment by kuon** [comment] 2022-06-16 03:54
Shouldn't it be OK to upgrade now as the mentioned issue seems to be fixed?

**Comment by jamwaffles** [comment] 2022-06-16 08:06
That PR was merged some time ago, but there hasn't been an stm32-rs release since, so we need to wait for that.

**Closed** 2022-08-15 10:31 UTC
